Repository DoubleV37/ft_transcendence, pull requests merged in 2024-04, with the labels that each got.

#82 78-Hotfix Resolved
  .gitignore
  Django_data/Project/middleware.py
  Django_data/apps/Auth/views.py
  Django_data/static/js/Tools/SinglePage.js
  Django_data/static/js/main.js
  initBranch
Labels: bug

#85 84 feature/game settings/front
  .gitignore
  Django_data/Project/middleware.py
  Django_data/apps/Game/urls.py
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Modes_CallBack.js
  Django_data/static/js/Game/Modes_Events.js
  Django_data/static/js/Game/Parameters.js
  Django_data/static/js/Game/Parameters_CallBack.js
  Django_data/static/js/Game/Parameters_Events.js
  Django_data/static/js/Home/Home_Events.js
  Django_data/static/js/Tools/Tools.js
  Django_data/static/js/User/Parameters_Events.js
  Django_data/static/js/main.js
  Django_data/templates/Game/Modes.html
  Django_data/templates/Game/Parameters.html
  Django_data/templates/Home/head.html
  Django_data/templates/Profile/Settings.html
Labels: enhancement

#89 86 hotfixsessionlessrequestbug
  Django_data/Project/middleware.py
  Django_data/Project/settings.py
  Django_data/apps/Auth/views.py
  Django_data/static/js/Home/Header_Events.js
  Django_data/static/js/Tools/SinglePage.js
  Django_data/static/js/Tools/Tools.js
Labels: bug

#95 83 feature/game settings/master
  .gitignore
  Django_data/Project/middleware.py
  Django_data/apps/Game/urls.py
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Modes_CallBack.js
  Django_data/static/js/Game/Modes_Events.js
  Django_data/static/js/Game/Parameters.js
  Django_data/static/js/Game/Parameters_CallBack.js
  Django_data/static/js/Game/Parameters_Events.js
  Django_data/static/js/Home/Home_Events.js
  Django_data/static/js/Tools/Tools.js
  Django_data/static/js/User/Parameters_Events.js
  Django_data/static/js/main.js
  Django_data/templates/Game/Modes.html
  Django_data/templates/Game/Parameters.html
  Django_data/templates/Home/head.html
  Django_data/templates/Profile/Settings.html
Labels: enhancement, code

#98 64 feature/friend list/master
  Django_data/Project/settings.py
  Django_data/Project/urls.py
  Django_data/apps/Auth/models.py
  Django_data/apps/Auth/views.py
  Django_data/apps/FriendsList/__init__.py
  Django_data/apps/FriendsList/admin.py
  Django_data/apps/FriendsList/apps.py
  Django_data/apps/FriendsList/migrations/__init__.py
  Django_data/apps/FriendsList/models.py
  Django_data/apps/FriendsList/tests.py
  Django_data/apps/FriendsList/tools.py
  Django_data/apps/FriendsList/urls.py
  Django_data/apps/FriendsList/views.py
  Django_data/apps/Home/views.py
  Django_data/apps/Profile/views.py
  Django_data/apps/Twofa/serializers.py
  Django_data/apps/Twofa/views.py
  Django_data/static/css/animations.css
  Django_data/static/css/buttons.css
  Django_data/static/css/home.css
  Django_data/static/css/modal.css
  Django_data/static/css/profile.css
  Django_data/static/css/tournament.css
  Django_data/static/images/alone.webp
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Home/Header_Events.js
  Django_data/static/js/Modals_Init.js
  Django_data/static/js/Tools/SinglePage.js
  Django_data/static/js/Tools/Tools.js
  Django_data/static/js/User/Avatar_Modal.js
  Django_data/static/js/User/Friends.js
  Django_data/static/js/User/Friends_Callback.js
  Django_data/static/js/User/Friends_Events.js
  Django_data/static/js/User/Friends_Tools.js
  Django_data/static/js/main.js
  Django_data/templates/Auth/SignIn.html
  Django_data/templates/Auth/SignUp.html
  Django_data/templates/FriendList/FriendsList.html
  Django_data/templates/FriendList/RequestList.html
  Django_data/templates/Game/Modes.html
  Django_data/templates/Game/Parameters.html
  Django_data/templates/Home/footer.html
  Django_data/templates/Home/head.html
  Django_data/templates/Home/header.html
  Django_data/templates/Home/home.html
  Django_data/templates/Profile/User_Settings.html
Labels: enhancement, code

#100 multiplayer
  Django_data/apps/Game/consumers_matchmaking.py
  Django_data/apps/Game/consumers_multiplayer.py
  Django_data/apps/Game/routing.py
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Game_Display.js
  Django_data/static/js/Game/Game_Events.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/static/js/Game/Matchmaking_Events.js
  Django_data/static/js/Game/Modes_CallBack.js
  Django_data/static/js/Home/Header_Events.js
  Django_data/static/js/Tools/SinglePage.js
  Django_data/static/js/Tools/Tools.js
  Django_data/static/js/main.js
  Django_data/templates/Game/gamePage.html
  Django_data/templates/Game/matchmaking.html
  Django_data/templates/Game/multiGamePage.html
  Django_data/templates/Home/head.html
  Services/Uvicorn/entrypoint.sh
Labels: enhancement

#102 Multionline
  Django_data/apps/Game/consumers.py
  Django_data/apps/Game/consumers_multiplayer.py
  Django_data/apps/Game/models.py
  Django_data/static/js/Game/Game_Events.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/templates/Game/gamePage.html
  Django_data/templates/Game/multiGamePage.html
Labels: enhancement

#104 Multionline
  Django_data/apps/Game/consumers_multiplayer.py
  Django_data/apps/Game/models.py
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Game_Events.js
  Django_data/static/js/Game/Parameters_CallBack.js
Labels: enhancement

#105 103 feature/foreign profil/master
  Django_data/Project/middleware.py
  Django_data/apps/Auth/models.py
  Django_data/apps/Auth/urls.py
  Django_data/apps/Auth/views.py
  Django_data/apps/FriendsList/tools.py
  Django_data/apps/FriendsList/urls.py
  Django_data/apps/FriendsList/views.py
  Django_data/apps/Profile/views.py
  Django_data/static/css/buttons.css
  Django_data/static/css/profile.css
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Parameters_CallBack.js
  Django_data/static/js/Tools/Tools.js
  Django_data/static/js/User/Friends.js
  Django_data/static/js/User/Friends_Callback.js
  Django_data/static/js/User/Profile_Callback.js
  Django_data/static/js/User/Profile_Events.js
  Django_data/static/js/main.js
  Django_data/templates/Game/Modes.html
  Django_data/templates/Game/Parameters.html
  Django_data/templates/Profile/Friends_Profile.html
  Django_data/templates/Profile/Profile.html
Labels: enhancement, code

#112 107 feature/skin/master
  Django_data/apps/Auth/models.py
  Django_data/apps/Profile/urls.py
  Django_data/apps/Profile/views.py
  Django_data/static/css/animations.css
  Django_data/static/css/buttons.css
  Django_data/static/css/footer.css
  Django_data/static/css/header.css
  Django_data/static/css/home.css
  Django_data/static/css/modal.css
  Django_data/static/css/parameters.css
  Django_data/static/css/profile.css
  Django_data/static/css/settings.css
  Django_data/static/css/sign_in.css
  Django_data/static/css/sign_up.css
  Django_data/static/css/skins.css
  Django_data/static/css/tournament.css
  Django_data/static/images/skins/background/BG_Forest.png
  Django_data/static/images/skins/background/BG_LoFi.png
  Django_data/static/images/skins/background/BG_Space.png
  Django_data/static/images/skins/background/backgroundSelectForest.png
  Django_data/static/images/skins/background/backgroundSelectLoFi.png
  Django_data/static/images/skins/background/backgroundSelectSpace.png
  Django_data/static/images/skins/ball/Ball_Blackhole.png
  Django_data/static/images/skins/ball/Ball_Cat.png
  Django_data/static/images/skins/ball/Ball_Sushi.png
  Django_data/static/images/skins/ball/ballSelectBlackhole.png
  Django_data/static/images/skins/ball/ballSelectCat.png
  Django_data/static/images/skins/ball/ballSelectSushi.png
  Django_data/static/images/skins/paddle/Paddle_Amethyst.png
  Django_data/static/images/skins/paddle/Paddle_Grass.png
  Django_data/static/images/skins/paddle/Paddle_Snow.png
  Django_data/static/images/skins/paddle/paddleSelectAmethyst.png
  Django_data/static/images/skins/paddle/paddleSelectGrass.png
  Django_data/static/images/skins/paddle/paddleSelectSnow.png
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Tools/Tools.js
  Django_data/static/js/User/Profile_Callback.js
  Django_data/static/js/User/Skins.js
  Django_data/static/js/main.js
  Django_data/templates/Home/head.html
  Django_data/templates/Profile/Skins.html
Labels: enhancement, sub-dev, code

#114 113 hotfix/signout
  Django_data/static/css/header.css
  Django_data/static/js/Home/Header_Events.js
  Django_data/static/js/Home/Home_Events.js
  Django_data/templates/Home/header.html
  Django_data/templates/Home/home.html
Labels: bug

#121 Multionline improve
  Django_data/apps/Game/consumers_matchmaking.py
  Django_data/apps/Game/consumers_multiplayer.py
  Django_data/apps/Game/models.py
  Django_data/apps/Game/views.py
  Django_data/static/js/Game/Game_Events.js
  Django_data/static/js/Game/Game_Socket.js
  Makefile
Labels: enhancement
