Repository DoubleV37/ft_transcendence, pull requests merged in 2024-05, with the labels that each got.

#128 Multionline - OK but still bugged
  Django_data/Project/settings.py
  Django_data/apps/Game/consumers_matchmaking.py
  Django_data/apps/Game/consumers_multiplayer.py
  Django_data/apps/Game/models.py
  Django_data/apps/Game/pong.py
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Game_Events.js
  Django_data/static/js/Game/Game_Skins.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/static/js/Game/Matchmaking_Events.js
  Django_data/static/js/Tools/SinglePage.js
Labels: EndTask

#134 132 feature/improvedbgame/main
  Django_data/apps/Game/consumers.py
Labels: enhancement

#143 Front game speed and stats update
  Django_data/apps/FriendsList/views.py
  Django_data/apps/Game/consumers.py
  Django_data/apps/Game/pong.py
  Django_data/static/css/game.css
  Django_data/static/css/profile.css
  Django_data/static/images/cryptoadz-gremplin.gif
  Django_data/static/images/darth-vader.gif
  Django_data/static/images/ghost-phantom.gif
  Django_data/static/images/matchmaking.gif
  Django_data/static/images/purple-bat.gif
  Django_data/static/images/smolverse-smol.gif
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/static/js/Game/Gameboard_Events.js
  Django_data/static/js/Game/Stats_Events.js
  Django_data/static/js/User/Friends.js
  Django_data/templates/FriendList/FriendsList.html
  Django_data/templates/Game/Board.html
  Django_data/templates/Game/Stats.html
  Django_data/templates/Game/gamePage.html
Labels: enhancement, code

#144 Multi V2
  Django_data/apps/Auth/views.py
  Django_data/apps/Game/consumers_matchmaking.py
  Django_data/apps/Game/consumers_multiplayer.py
  Django_data/apps/Game/routing.py
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Game_Events.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/static/js/Game/Matchmaking_Events.js
  Django_data/static/js/Game/Modes_CallBack.js
  Django_data/static/js/Game/Parameters_CallBack.js
  Django_data/static/js/main.js
  Makefile
  Services/NginxReverseProxy/nginx.conf
  Services/PongServer/Dockerfile
  Services/PongServer/ServerFile/db_game.py
  Services/PongServer/ServerFile/game.py
  Services/PongServer/ServerFile/global_var.py
  Services/PongServer/ServerFile/loop_game.py
  Services/PongServer/ServerFile/matchmaking.py
  Services/PongServer/ServerFile/pong.py
  Services/PongServer/ServerFile/server.py
  Services/PongServer/requirements.txt
  docker-compose.yml
Labels: enhancement, sub-dev, EndTask

#146 Elk
  .env
  Django_data/Project/settings.py
  Django_data/gunicorn.conf
  Makefile
  Services/Elasticsearch/setup.sh
  Services/Gunicorn/entrypoint.sh
  Services/Gunicorn/requirements.txt
  Services/Logstash/logstash_gunicorn.conf
  Services/Logstash/logstash_nginx.conf
  Services/NginxReverseProxy/nginx.conf
  Services/Rsyslog/Dockerfile
  Services/Rsyslog/rsyslog.conf
  Services/Uvicorn/requirements.txt
  docker-compose.yml
Labels: enhancement, code, EndTask

#152 Front modal rework
  Django_data/apps/Dashboard/stat_fct.py
  Django_data/apps/FriendsList/tools.py
  Django_data/apps/Home/views.py
  Django_data/apps/Profile/views.py
  Django_data/static/css/game.css
  Django_data/static/css/header.css
  Django_data/static/css/profile.css
  Django_data/static/images/Baccara.png
  Django_data/static/images/BackArrow.svg
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/static/js/Game/Stats_Events.js
  Django_data/static/js/User/Friends_Events.js
  Django_data/static/js/User/Profile_Callback.js
  Django_data/static/js/User/Profile_Events.js
  Django_data/templates/Auth/SignIn.html
  Django_data/templates/Auth/SignUp.html
  Django_data/templates/FriendList/FriendsList.html
  Django_data/templates/Game/Board.html
  Django_data/templates/Game/Modes.html
  Django_data/templates/Game/Parameters.html
  Django_data/templates/Game/Stats.html
  Django_data/templates/Game/gamePage.html
  Django_data/templates/Game/matchmaking.html
  Django_data/templates/Game/multiGamePage.html
  Django_data/templates/Home/header.html
  Django_data/templates/Profile/Profile.html
  Services/PongServer/ServerFile/db_game.py
Labels: EndTask

#148 145 feature/global stats/master
  Django_data/apps/Dashboard/models.py
  Django_data/apps/Dashboard/stat_fct.py
  Django_data/apps/Dashboard/urls.py
  Django_data/apps/Dashboard/views.py
  Django_data/apps/Game/consumers.py
  Django_data/static/js/Game/Stats_Events.js
  Django_data/templates/Game/Stats.html
  Services/PongServer/ServerFile/db_game.py
Labels: enhancement, code

#165 Support on all device
  Django_data/apps/Home/views.py
  Django_data/static/js/GLOBAL_Variables.js
  Django_data/static/js/Game/Bracket_Event.js
  Django_data/static/js/Game/Game_Events.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/static/js/Game/Matchmaking_Events.js
  Django_data/static/js/Game/Modes_CallBack.js
  Django_data/static/js/Game/Parameters_Events.js
  Django_data/static/js/Game/Tournament_Event.js
  Django_data/static/js/Game/Tournament_Game.js
  Django_data/static/js/Home/Header_Events.js
  Django_data/static/js/Home/Home_Events.js
  Django_data/static/js/User/Profile_Callback.js
  Django_data/static/js/User/Settings_Callback.js
  Django_data/templates/Auth/SignIn.html
  Django_data/templates/Auth/SignUp.html
  Django_data/templates/Errors/404.html
  Django_data/templates/Game/Board.html
  Django_data/templates/Game/Bracket.html
  Django_data/templates/Game/Modes.html
  Django_data/templates/Game/Parameters.html
  Django_data/templates/Game/Stats.html
  Django_data/templates/Game/Tournament.html
  Django_data/templates/Game/gamePage.html
  Django_data/templates/Game/matchmaking.html
  Django_data/templates/Game/multiGamePage.html
  Django_data/templates/Home/head.html
  Django_data/templates/Home/header.html
  Django_data/templates/Profile/Avatar.html
  Django_data/templates/Profile/Friends_Profile.html
  Django_data/templates/Profile/GameHistory.html
  Django_data/templates/Profile/Profile.html
  Django_data/templates/Profile/Skins.html
  Django_data/templates/Profile/enable_2fa.html
Labels: EndTask

#166 158 feature monitoring system
  Makefile
  Services/Grafana/DB_Dashboard.json
  Services/Grafana/ServMetrics_Dashboard.json
  Services/Grafana/grafana.ini
  Services/NginxReverseProxy/nginx.conf
  Services/Prometheus/alert.rules.yml
  Services/Prometheus/prometheus.yml
  docker-compose.yml
Labels: enhancement, code, EndTask

#167 96 feature/rules usercreation/master
  Django_data/Project/middleware.py
  Django_data/Project/settings.py
  Django_data/apps/Auth/forms.py
  Django_data/apps/Auth/models.py
  Django_data/apps/Auth/validators.py
  Django_data/apps/Auth/views.py
  Django_data/apps/Dashboard/tools.py
  Django_data/apps/Profile/views.py
  Django_data/avatars/ForbiddenDeletion/default.png
  Django_data/static/css/game.css
  Django_data/static/css/home.css
  Django_data/static/css/modal.css
  Django_data/static/css/sign_in.css
  Django_data/static/css/sign_up.css
  Django_data/static/css/tournament.css
  Django_data/static/js/Game/Bracket_Event.js
  Django_data/static/js/Game/Game_AI.js
  Django_data/static/js/Game/Game_Socket.js
  Django_data/static/js/Modals_Init.js
  Django_data/static/js/Tools/Tools.js
  Django_data/static/js/User/Avatar_Modal.js
  Django_data/static/js/User/Friends_Tools.js
  Django_data/templates/FriendList/FriendsList.html
  Django_data/templates/FriendList/RequestList.html
  Django_data/templates/Game/Board.html
  Django_data/templates/Game/Bracket.html
  Django_data/templates/Home/footer.html
  Django_data/templates/Home/head.html
  Django_data/templates/Home/header.html
  Django_data/templates/Profile/Avatar.html
  Services/Gunicorn/entrypoint.sh
  Services/PongServer/ServerFile/loop_game.py
Labels: enhancement

#170 Feature/secure kibana
  Makefile
  Services/NginxReverseProxy/nginx.conf
  docker-compose.yml
Labels: enhancement

#175 fix touch screen game
  Django_data/static/js/Game/Game_Events.js
Labels: EndTask
